name: Deploy Backend

on:
  # push:
  #   branches:
  #     - masters
  #   paths:
  #     - 'backend/**'
  #     - '.github/workflows/backend.yml'
  #     - '.github/workflows/_reusable-deploy.yml'
  workflow_dispatch:
permissions:
  contents: read
  id-token: write
  security-events: write

jobs:
  deploy-backend:
    uses: ./.github/workflows/_reusable-deploy.yml
    with:
      deployment_type: backend
      environment: development   
      app_path: ./backend
      app_name: backend-app
      artifact_name: backend-build
      region: asia-south1
      artifact_repo: backendrepo

    secrets:
      GCP_PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
      WORKLOAD_IDENTITY_PROVIDER: ${{ secrets.WORKLOAD_IDENTITY_PROVIDER }}
      GCP_SERVICE_ACCOUNT: ${{ secrets.GCP_SERVICE_ACCOUNT }}
      FRONTEND_URL: ${{ secrets.FRONTEND_URL }}
      API_BASE_URL: ${{ secrets.API_BASE_URL }}
      