name: Deploy Frontend

on:
  # push:
  #   branches:
  #     - master
  #   paths:
  #     - 'frontend/**'
  #     - '.github/workflows/frontend.yml'
  #     - '.github/workflows/_reusable-deploy.yml'
#task3
  workflow_dispatch:
permissions:
  contents: read
  id-token: write
  security-events: write
jobs:
  deploy-frontend:
    uses: ./.github/workflows/_reusable-deploy.yml
    with:
      deployment_type: frontend
      environment: development
      app_path: ./frontend
      app_name: frontend-app
      artifact_name: frontend-build
      region: asia-south1
      GCS_BUCKET_NAME: frontend-123
    
    secrets:
      GCP_PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
      WORKLOAD_IDENTITY_PROVIDER: ${{ secrets.WORKLOAD_IDENTITY_PROVIDER }}
      GCP_SERVICE_ACCOUNT: ${{ secrets.GCP_SERVICE_ACCOUNT }}
      API_BASE_URL: ${{ secrets.API_BASE_URL }}